### PR TITLE
fix: Recalculate layer scaling using last rendered size scale factors

### PR DESCRIPTION
**Pull request by saif-ellafi**
Hello,

I am honestly not sure if this is the right approach, as I am a bit new around here. But, this solves a problem where editing image states across different screen size/devices would not properly adjust layer scale and position.

This also alters the data structure of import of export, so checking whether the default values are sane is also appreciated. So far I have used a Size.zero absence of this field in previous JSON files for retro-compatibility. The recalculate function takes care of this case so it works fine (in my testing) with older versions.

**However:** The proper calculation will only work in newly exported images, since we didn't have the `lastRenderedSize` in the image states of the past. However it will not fail, it will be just as it was, retrocompatible.

### Before (problem)
image
image

### After (solution)
image
image

### CODE REVIEW

**Review by hm21 — CHANGES_REQUESTED** [review]
Thanks for the PR.

I tested it, but unfortunately, it still doesn't work correctly. You can try the [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/import_export_example.dart) import/export.

If you resize the window in that way the image doesn’t fit to the editor size, everything works fine. However, if you resize the window in the same direction like the image fit it didn't work.
For example, if the image fits the height of the editor, you can change the width of the window and everything will work fine, but if you change the height of the window, it will also move the layers incorrectly.

It seems to me that resizing from layers doesn't work properly. Maybe we just need to fix that part to make it work.

**Comment by saif-ellafi** [comment]
Will check @hm21 - but for me it works fine really, in all directions, or maybe I am not understanding your case.

By the way, are you sure you re-exported in the example? Will test now, but this fix **will not work** in previously exported files (i.e. `import_history_demo_data` because the old exported data does not include the `lastRenderedImgSize` which is necessary to compute proper calculations.

Maybe we need to update the example only, otherwise it will just work like it was in the past :)

under 
```
{
'imgSize': {'width': 1024.0, 'height': 1792.0},
'lastRenderedImgSize`: {...}
}
```

Where this `lastRenderedImgSize` represents the rendered size at which the layers were originally drawn.

Could we regenerate `import_history_demo_data`? If not we can estimate the size at which the layers were originally rendered :) then the example will work.

**Comment by saif-ellafi** [comment]
Hi @hm21 - fixed Demo data so the example works! 

It is tempting to use `imgSize` as default value, but it could disrupt layers for very large images developed in small screen devices. So I think the current state is the best we can do :)

**Review by hm21 — APPROVED** [review]
With the updated demo history data, everything seems to be working correctly. I made some minor adjustments to the version number and improved the quality of the `ImportStateHistory.fromMap` implementation, as the previous code there from me was a bit suboptimal/ trash.

In the future I will also rewrite the state history a bit cuz that code was planned before for templates. I just used it then as state history, but to be honest, it makes no sense in the history to store everything again after you made changes.

For now, I’ll approve this and proceed with the release. Great job on your part!

**Comment by saif-ellafi** [comment]
Absolutely wonderful! Thank you so much.

**Pull request merged**
