### PR TITLE
feat(serializeFlag): Enable a flag to not serialize Widgets

### PR DESCRIPTION
**Pull request by saif-ellafi**
Hello,

This is rather a prompt to discuss a feature, more than a full blown feature PR on itself.

I am currently storing Stickers in my app, and loading the `StickerLayerData` from source files. The current serialization is hardcoded to png and the history json files increase their size exponentially if storing the state.

This PR adds a flag that allows skipping serialization of Widget if the developer takes care of their own Sticker layers. A better feature would be to allow storing other than serialized widget, for example file paths to load from instead.

Currently, upon restoring the state, I am overriding the stickers with an Image of my own, i.e.

```dart
    if (image.historyImgLayers != null) {
      image.historyImgLayers!.forEach((layerIndex, imageName) {
        ImageMetadata loadedImage = galleryImages.firstWhere(
          (image) => image.filename == imageName,
          orElse: () {
            return ImageMetadata.fromFileNameInGame(imageName);
          }
        );
        // replace all sticker layers with the original image using the active layer index
        var baseLayers = history?.stateHistory.first.layers;
        if (baseLayers != null && baseLayers.length > layerIndex) {
          var baseLayer = baseLayers[layerIndex];
          if (baseLayer is StickerLayerData) {
            baseLayers[layerIndex] = baseLayer.copyWith(
              sticker: Image.memory(
                loadedImage.image,
                fit: BoxFit.cover,
                width: loadedImage.size.width.toDouble(),
                height: loadedImage.size.height.toDouble(),
              ),
            );
          }
        }
      });
    }
```

Definitely not fancy, but work blazing well, history state files are very lightweight this way, and I don't have to care about layer compression and quality.

image

Open to discuss!
Cheers and thanks again for the awesome library

### CODE REVIEW

**Comment by hm21** [comment]
Hi @saif-ellafi,

Apologies for the delayed response. I've been quite busy with several other projects. However, I’ll review it today and see if there’s a way to extend your solution or if that's already the best solution.

**Comment by hm21** [comment]
Hi @saif-ellafi,

I’ve made some improvements that now allow you to include your own sticker references within `ExportEditorConfigs` using the `stickerReference` property. It’s important to note that the key in the map must match the sticker ID.

I haven’t had a chance to test it yet, but I believe this solution should work. Let me know your thoughts!

**Comment by saif-ellafi** [comment]
Magical! I am curious, will take a look and give it a try. My uttermost goal is to not serialize any images inside an image, nor the layers in the state. For various reasons, but most importantly, to:

1. Avoid image quality loss
2. Load state rather than image
3. Avoid large image png size when the app holds the image source of the layers

Will test soon and come back - but this should also help at: https://github.com/hm21/pro_image_editor/issues/174

**Comment by saif-ellafi** [comment]
Hey @hm21 

Testing quite a bit, I have some feedback to share:

**First thoughts** - indeed it feels convenient to be able to store in the state an ExportStickerModel. However the IDs look scary since per what I've seen, layers get new IDs when the editor loads from state, but if this preserves state and IDs of stickers, then great. Second, the flag to not serialize, just as the original PR, is useful already.

**Regarding the usage of the stickerReference**

Here things get complicated, but I was underways already doing something similar:

### Challenge 1

The first issue is that `StickerLayerData` does not preserve the `EditorImage` per se, so I cannot retrieve the path or source of the layer. To come around this limitation, I am doing a two-steps hack:
1.
a. On the "Add File" CustomWidget (following the Gallery example), I intercept and internally save the `imagePath`.
b. For the Gallery widget, in the `onTap` of choosing an image from the gallery, I capture here the `imagePath`.

2. I listen the call back `onAddLayer` to capture the id or index of the layer, so I can combine this metadata along the imagePath temporarily stored from step 1.

Only now, since I have an in-memory Map with the ID <-> `imagePath`, I can proceed to the `onImageEditingComplete` to save the state, and can now build the `stickerReference` with something like this:

```dart
var stickerLayers = editorKey.currentState?.activeLayers.whereType<StickerLayerData>();
Map<String, ExportStickerModel> stickerReference = {};
stickerLayers?.forEach((stickerLayer) {
  var stickerIndex = editorKey.currentState?.activeLayers.indexOf(stickerLayer);
  stickerReference[stickerLayer.id] = ExportStickerModel(
    image: EditorImage(file: File(
      temporaryLayerMeta![stickerIndex]! // <---- this internally retrieves the imagePath
    ))
  );
});
editorKey.currentState?.exportStateHistory(
  configs: ExportEditorConfigs(
    historySpan: ExportHistorySpan.current,
    convertStickerToImage: false,
    stickerReference: stickerReference
  )
).then((stateHistory) {
// rest of the code ...
}
```

So, bottom line, feedback for this first matter, would it be helpful and useful to somehow store StickerLayers EditorImage or any reference to the source, inside `StickerLayerData` ? This would save this pain on the app side, so to say, allowing the developr to mor easily build up the `stickerReference`

_Possible solution:_ Find a way to include source image metadata inside `StickerLayerData`

### Challenge 2 (specifically for EditorImage using file)

Even if this seems happy and fine, there is a big second problem. When I load the state, the `imagePath` I have stored, are only relative to the user who saved them, and they need to be completed/processed by the app, to adapt the path to the existing device setting or user configuration.

This I did not find a way to come around, but I image we will need some sort of "unload" function inside `ImportEditorConfigs` or `StateHistoryConfigs`, where you can allow us the developers, to make adjustments to the StickerLayers? Maybe a function. Because otherwise the stored `imagePath` will be meaningless outside the device where the state was saved to, I think.

Currently, in my own app, when I load the history, I am manually processing the self-stored `imagePath` with some function `ImageMetadata.fromFileNameInGame(imagePath);`  and then modify the layer myself in the state before loading the editor. Also ugly, in a way, but works.

Bottom line, I am not sure how universally useful will the `EditorImage` be, for storing file paths, without allowing the developer to decide how to process it? I guess it will work just fine with `assetPath` or `networkUrl` so this may only be my specific problem and not really relevant. I imagine however both `File` and `NetworkUrl` could use some sort of function to process them further (i.e. what if the NetworkUrl requires some specific credentials or headers?)

_Possible solution 1_ : include a processing function of EditorImage => EditorImage where developers could apply changes to the source of the sticker layers, and add for example changes to File Paths or Network URL endpoints and so on, so the images load properly.
_Possible solution 2_ : Instead of saving `EditorImage` in the `ExportStickerModel`, save something else? For example a Map<String, String> so developer can store whatever they want, then offer a function Map<String, String> => EditorImage in the `ImportEditorConfigs` to parse this?

### Challenge 3 (simple one)

The editor currently crashes when it fails to restore layers and their Files do not exist (i.e. wrong path, or equivalent). Maybe it should load a dummy layer or not load the layer at all.



-- long message, but hopefully useful
But in the meantime, I can survive just fine with the flag, since all of the above I am currently implementing and hacking on my side.

**CONCLUSION**: I could not benefit from `stickerReferences`, but the flag to disable serialization `convertStickerToImage` (I think it should be plural, by the way), is already very very useful.

Best regards and Christmas!

**Comment by saif-ellafi** [comment]
I am truly sorry. I forced pushed a wrong commit to the branch and erased history :/ I didn't know your commits link to my fork, so double mistake 🥇 
I'll reopen a PR as I needed this on my end, but I can't replicate your original suggestions :(
Will do it from 7.0.0 though.

**Pull request closed without merging**
